table Product
	lineageTag: 21476e4b-021b-451b-8fbc-82187e5afe36

	column PL4
		dataType: string
		lineageTag: 0ec4fdc5-65d9-45f3-aac0-377f5940d8ca
		summarizeBy: none
		sourceColumn: PL4

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: f5aabe91-742c-4726-b305-933ce13519ce
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 295297c8-9a9f-406e-8547-c8e0599bbeaf
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: a195fc51-9db5-4fa4-9b6b-3ef55f7516f9
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\!BI Power\R2G\Source_B.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Product_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"PL4", type text}, {"SKU", type text}, {"Product Name", type text}, {"Description", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

