table Sales
	lineageTag: 7298709b-d23b-4d1d-82ad-dcb4f034863f

	column SKU
		dataType: string
		lineageTag: 66001d4e-5510-4246-a5e3-00dcf7db544a
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column 'NS in €'
		dataType: double
		lineageTag: af6faf71-041d-453d-af22-fd39816aefba
		summarizeBy: sum
		sourceColumn: NS in €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTY
		dataType: double
		lineageTag: eedb0303-5017-40a8-9911-8cb8f36b933f
		summarizeBy: sum
		sourceColumn: QTY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Engineer = ```
			
			    LOOKUPVALUE(
			        Engi[Engi],
			        Engi[SKU], Sales[SKU]
			    )
			```
		lineageTag: 93bba016-a22c-491d-867c-396e3e914c4b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\!BI Power\R2G\Source_B.xlsx"), null, true),
				    Sales_Sheet = Source{[Item="Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SKU", type text}, {"NS in €", type number}, {"QTY", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

